# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:8.2.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
RUN mkdir -p logs
RUN touch logs/service.log
